const RULER_OVERLAY_COLOR = '#0f766e';

const RULER_OVERLAY_DASH = [6, 4];

const RULER_OVERLAY_STROKE_WIDTH = 1;

const RULER_OVERLAY_LABEL_GAP = 8;

const RULER_OVERLAY_LABEL_PADDING = 4;

const RULER_OVERLAY_BG = '#0f766e';

const RULER_OVERLAY_TEXT_COLOR = '#ffffff';

const RULER_BAR_THICKNESS = 20;

/** Actual spacing is rounded to a "nice" 1-2-5 step, so this is a target, not an exact value. */
const RULER_BAR_MAJOR_TICK_TARGET_PX = 80;

const RULER_BAR_MINOR_TICKS_PER_MAJOR = 5;

const RULER_BAR_MINOR_TICK_COLOR = '#ccc';

const RULER_BAR_MAJOR_TICK_COLOR = '#888';

const RULER_BAR_LABEL_COLOR = '#555';

const RULER_BAR_FONT_SIZE = 9;

const RULER_BAR_GUIDE_COLOR = '#999';

const RULER_BAR_GUIDE_OPACITY = 0.35;

export {
  RULER_OVERLAY_COLOR,
  RULER_OVERLAY_DASH,
  RULER_OVERLAY_STROKE_WIDTH,
  RULER_OVERLAY_LABEL_GAP,
  RULER_OVERLAY_LABEL_PADDING,
  RULER_OVERLAY_BG,
  RULER_OVERLAY_TEXT_COLOR,
  RULER_BAR_THICKNESS,
  RULER_BAR_MAJOR_TICK_TARGET_PX,
  RULER_BAR_MINOR_TICKS_PER_MAJOR,
  RULER_BAR_MINOR_TICK_COLOR,
  RULER_BAR_MAJOR_TICK_COLOR,
  RULER_BAR_LABEL_COLOR,
  RULER_BAR_FONT_SIZE,
  RULER_BAR_GUIDE_COLOR,
  RULER_BAR_GUIDE_OPACITY,
};
